server:
  port: 2170
  servlet:
    context-path: /rest/v1
  
spring:
  application:
    name: CART-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/cart
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka